# Generated by Django 4.2.6 on 2024-03-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_dish_team_profile_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
